apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gbl-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-controller-custom"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: gblwordpress
          servicePort: 80